[phases.build]
cmds = [
  "npm install --prefix client",
  "npm install --prefix server",
  "npm run build --prefix client",
  "npm run build --prefix server"
]

[start]
cmd = "node vectron-app/server/dist/index.js"
